title: Kevin Miller
description: Engineering Leadership | AI | Security | Strategy
baseurl: "" # leave empty unless in a subdir
url: "https://kemiller2002.github.io"

# Remove the remote_theme line
# remote_theme: pages-themes/slate

theme: minima # or omit this if you’re using your own layout

plugins:
  - jekyll-feed
  - jekyll-titles-from-headings
