source "https://rubygems.org"

# Local Jekyll for development
gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.8"

# Theme (if you use minima)
gem "minima", "~> 2.5"

# Plugins
gem "jekyll-feed", "~> 0.12"
gem "jekyll-titles-from-headings"
gem "jekyll-seo-tag"       # 👈 add this line
# Platform-specific stuff (fine to keep)
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", platforms: [:mingw, :x64_mingw, :mswin]
